#%%define debug_package %{nil}
%global module pygame
%global mod %(m=%{module}; echo ${m:0:1})

Summary:	Python module for interfacing with the SDL multimedia library
Name:		%{module}
Version:	2.1.2
Release:	1
Source0:	https://github.com/%{name}/%{name}/archive/%{version}/%{name}-%{version}.tar.gz
#Source0:	https://pypi.io/packages/source/%{mod}/%{module}/%{module}-%{version}.tar.gz
#Source100:	%{name}.rpmlintrc
#Patch0:		pygame-1.9.1-config.patch
License:	LGPLv2+
Group:		System/Libraries
URL:		http://pygame.org/

BuildRequires:	pkgconfig(python3)
BuildRequires:	python3dist(cython)
#BuildRequires:	python3dist(pip)
BuildRequires:	python3dist(setuptools)
#BuildRequires:	python3dist(wheel)
BuildRequires:	portmidi-devel
BuildRequires:	pkgconfig(freetype2)
BuildRequires:  pkgconfig(libjpeg)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(sdl2)
BuildRequires:	pkgconfig(SDL2_image)
BuildRequires:	pkgconfig(SDL2_mixer)
BuildRequires:	pkgconfig(SDL2_ttf)
BuildRequires:	pkgconfig(x11)
BuildRequires:	smpeg-devel
BuildRequires:	fonts-ttf-freefont

Requires:	fonts-ttf-freefont
#Provides:	python-pygame


%description
pygame is a Python wrapper module for the SDL multimedia library,
written by Pete Shinners. It contains python functions and classes that
will allow you to use SDL's support for playing cdroms, audio and video
output, and keyboard, mouse and joystick input. pygame also includes
support for the Numerical Python extension. pygame is the successor to
the pySDL wrapper project, written by Mark Baker.

Install pygame if you would like to write or play SDL games written in
the python language.

%files
%doc README.rst
%{py_platsitedir}/%{module}
%{py_platsitedir}/%{module}-%{version}-py%{py_ver}.egg-info

#---------------------------------------------------------------------------

%package doc
Summary:	Pygame documentation and example programs
Group:		Development/Python

%description doc
pygame is a Python wrapper module for the SDL multimedia library,
written by Pete Shinners. It contains python functions and classes that
will allow you to use SDL's support for playing cdroms, audio and video
output, and keyboard, mouse and joystick input. pygame also includes
support for the Numerical Python extension. pygame is the successor to
the pySDL wrapper project, written by Mark Baker.

Install pygame-doc if you need the API documentation and example
programs.

%files doc
%doc docs/
%doc examples/

#---------------------------------------------------------------------------

%package devel
Summary:	Pygame development headers
Group:		Development/Python

%description devel
pygame is a Python wrapper module for the SDL multimedia library,
written by Pete Shinners. It contains python functions and classes that
will allow you to use SDL's support for playing cdroms, audio and video
output, and keyboard, mouse and joystick input. pygame also includes
support for the Numerical Python extension. pygame is the successor to
the pySDL wrapper project, written by Mark Baker.

Install the devel package if you want to build programs with pygame.

%files devel
%{_includedir}/python%{py_ver}/%{name}/

#---------------------------------------------------------------------------

%prep
%autosetup -p1 -n %{module}-%{version}

# Drop pre-compiled Cython sources
rm $(grep -rl '/\* Generated by Cython')

%__python3 buildconfig/config.py
perl -pi -e 's|^(SDL = .*)|$1 -lm|;' Setup

# remove non-free stuff
rm -f src_c/ffmovie.[ch]

%build
%__python setup.py build cython

%install
%py_install

# use system font
ln -fs /usr/share/fonts/TTF/FreeSansBold.ttf %{buildroot}%{py3_platsitedir}/%{module}/freesansbold.ttf

